### ISSUE TITLE
Xinrochs (skeleton and dark knight version) can spawn randomly during Tomb quest

### ISSUE THREAD

**Issue by serin-delaunay** [Attnam/ivan#186]
On my XT run, I went to XT10 and killed Xinroch's ghost. Xinroch the skeletal warlord appeared later on the same level, carrying a non-quest ruby flaming sword. Before I traversed the portal, Xinroch the elder dark knight spawned on XT2 with the quest sword. The same monster with the same quest sword appeared as scripted on XT13. Both of these random spawns seem like bugs.

**Comment by fejoa** [comment]
Partially fixed by changes in #190. Next would be to prevent skeleton Xinroch from showing up in the Tomb, which we can potentially do with dungeon tags plus some fiddling with [summoning](https://github.com/Attnam/ivan/blob/master/Main/Source/human.cpp#L4519), but I don't really mind him there at the moment.

**Comment by fejoa** [comment]
Fixed by 695e95a
