### ISSUE TITLE
Breaking poly wand explosion crash

### ISSUE THREAD

**Issue by Coolthulhu** [Attnam/ivan#237]
Not sure about the exact mechanics, but it reproduces semi-reliably even without trying (ie. in regular game):
* Grab wands. Be sure to include polymorph and at least one damage wand (lightning, striking, fireballs). The more explosives the more likely it will trigger.
* Get exploded (activate a backpack)
* (Hopefully) You'll turn into something and then the game will crash

The last message hints at breaking wands, but not unambiguously: there is always a "wand breaks" message, but it isn't always the last message on the list.

Further possible hints:
* I was unable to reproduce this with wands on the floor, despite repeated attempts
* I was unable to reproduce this while already polymorphed

May take a few tries because it requires the wands to break - possibly in specific order.

**Comment by fejoa** [comment]
Awesome bug finding! Thanks for the hints!

**Comment by fejoa** [comment]
Is this possibly related to #107?

@emlai as an aside, what debug tools are you using?

**Comment by emlai** [comment]
@fejoa lldb.

> Is this possibly related to #107?

Quite likely.

**Comment by emlai** [comment]
Ok here's what's going on:
1. The explosion breaks the wand of polymorph, which causes the player to be polymorphed.
2. As a consequence of this, the old form of the player gets removed from the game and replaced with a new form.
3. Because the old form is removed from the game, its `SquareUnder[0]` is set to null in [char.cpp:7605](https://github.com/Attnam/ivan/blob/1d59ce1a787a713c196e58f5e640fdfeb2ce347a/Main/Source/char.cpp#L7605).
4. Finally the execution returns back to `character::GetHitByExplosion`, where `this` refers to the _old_ form, whose `SquareUnder[0]` is null.
5. Then [`GetArea()`](https://github.com/Attnam/ivan/blob/1d59ce1a787a713c196e58f5e640fdfeb2ce347a/Main/Source/char.cpp#L7171) gets called, which accesses `SquareUnder[0]`, and boom.

So this did originate in [this commit](https://github.com/Attnam/ivan/commit/0a73d297788cb0436516f5e1aab0c406284c7845#diff-4cadc0208ffad4bddcb5b649814f7d9bR7002) as found by @fejoa in #107.

**Comment by fejoa** [comment]
What fun! It does require a special set of circumstances to cause the bug. I wonder how best to fix it? We could revert the change, or change the change, or cause polymorphed characters to immediately initialize their square under?

**Comment by emlai** [comment]
I think the simplest working solution would be to just skip the `SpillBlood` if-statement if `SquareUnder[0]` is null.

We probably don't want to spill the blood _of_ the new form for the damage that was done to the old form. And trying to spill the blood of the old form on the new form would probably involve changing too much code and that would likely cause more bugs than it would fix.

Submitting a pull request…
