### ISSUE TITLE
Scrolls and books either ignite or burn away immediately during explosions!

### ISSUE THREAD

**Issue by rvanherel** [Attnam/ivan#29]

**Comment by Lum4r** [comment]
You can prevent that by storing them in an appropriate, inflammable container. I remember stuffing about 3 books and a dozen scrolls in a small lock-box. It just took an extra turn to take them out before I could read them.

**Comment by andrewtweber** [comment]
@Lum4r  yes but in the past, if you got hit by an explosion, you may lose 1 or 2 scrolls that were not protected but not all of them. Now with the fire subsystem everything instantly gets turned to ash.

**Comment by rvanherel** [comment]
Yeah, my problem description should have been more specific. I haven't put any randomizations into the fire subsystem yet because I'd like to be sure I am going to get flames when I blow things up.
It's not limited to books and scrolls either, basically any solid, inorganic material that can burn and that reaches its thermal limit, will ignite. So there needs to be some randomness included.

**Comment by rvanherel** [comment]
Fixed by this commit: https://github.com/Attnam/ivan/commit/3ec709c8e4e8dbf9a7480a76d1bc80c0e00625ce

**Comment by andrewtweber** [comment]
Just wondering, does the size of the explosion have an effect on this? Because the biggest nuisance I saw was that simply kicking a booby trapped door with a tiny explosion would burn my books away. I think the % chance of that happening should be way lower. For a big mine exploding though, then I can see even more than 50% of the books and scrolls burning.
