### ISSUE TITLE
The game needs upscaling options.

### ISSUE THREAD

**Issue by Asmageddon** [Attnam/ivan#324]
To put it simply: The tiles are too damn small for modern higher resolution monitor, and running the game in stretched fullscreen is an ugly, ugly hack.

Starting with obvious nearest neighbour, it'd be lovely to get hq2/3/4x, perhaps [xBRZ](https://sourceforge.net/projects/xbrz/).

Useful link for reference: https://github.com/libretro/common-shaders

I'm also pretty sure that MAME has a collection of scaling shaders, somewhere, but it's been so long since I last was involved in coding-related stuff that I don't have the links.

**Comment by AquariusPower** [comment]
I was reading the code, it is extremely hard to implement a change in the graphics current size. I got quite confused even from where to start doing it :(

Well, I have headaches with small graphics, so I implemented an ugly hack that changes the game layout to be like this:
![ivan 0 51_045](https://user-images.githubusercontent.com/17087075/37376341-8aa49e38-2702-11e8-9fb2-10205bad5021.jpg)

as you can see, I:
- lowered the visible dungeon size
- moved the look zoom streched picture and everything else.

That layout is perfect to fit in a 16:9 monitor, after you zoom your desktop using the OS feature, on linux compiz have it quite easy with Enhanced Zoom, I even scripted it to be automatic: it  zooms to a specific perfect location, lock the zoom so we can move the mouse too without changing the zoom position (I think in windows it is called magnifier).

**Comment by Asmageddon** [comment]
No matter how messy the code is, it _should_ be possible to replace rendering to the screen with rendering to a context/bitmap, and then upscaling that before rendering.

Of course, I'm not familiar with the codebase, maybe it isn't, but I think the possibility is worth investigating. People probably aren't going to be very happy about playing in an 800x600 fullscreen window on 4K displays. Heck, it's pretty jarring even on lower resolution screens.

**Comment by AquariusPower** [comment]
That is what I thought in the beginning. I just wanted to scale the full dungeon output x2.

We could probably intercept/redirect the final drawing (blitting), and apply some cool 2D auto art like hq4x, but... 

As I also read on Ivan3D wiki, that explosions would not be rendered, I thought that we would just create more complexity, more problems to be addressed.

Im not quite sure but I think the game updates only specific locations on the screen, unless the visible dungeon area is moved when we reach an egde.

This means, we would have to fastly fully draw the whole bitmap like 30 times per second to see all the minor effects happening on it. And I think new computers can do that, but old computers may not be able to.

Therefore this full visible drawn area scaling would be required to be **optional**.

In the other hand, to draw everything 32x32, would take more cpu and could be harder on older computers too.

Basically, by not fully knowing how it works, I just have more questions than answers. I had to give up because after reading the code for some time it got quite confusing, it is like 15+ years I dont code in C++, even using Eclipse IDE.

Anyway, I thought if we could just stretch each square by x2, (like is done with the look mode 'L' key in-game action, but it is x5), then it would draw only that square enlarged and that could be faster, despite I believe there is more coloring going on pixel by pixel and it may not work either, because it is all about 16x16.

They had plans for 32x32 graphics but never got coded...

Oh btw, Ivan is cool by it's graphics, and now sounds, but much more for the game play/mechanics itself. It should be recreated in a fully new game engine like UDK4 (but GPL isnt compatible with it) or some other. 
So, what I mean is: ppl is happy with the game play. 
And that is probably why we want better graphics and sfx :)

Unless someone can find a way to improve/stretch the graphics, that will provide at least what we already have (concerning gfx effects) as a start, with some easy moves like using the bitmap, the other options are really complicated.

I expect have given some tips from where to start trying to stretch the graphics, or at least allow us to use x2 or x3 etc input gfx files. If the 16x16 were 2 variables, it would probably be easy, but it is all hardcoded like that...

Someone correct me if I am wrong, I had some trouble following/reading the code.

**Comment by Asmageddon** [comment]
I really don't think a roguelike like IVAN would benefit from being rewritten in a game engine. On the other hand, it certainly could use the rendering code being rewritten if it's as bad as you say.

**Comment by AquariusPower** [comment]
well, the rendering is not actually bad, it is just I that had difficulty on following it...

anyway, I managed to prepare the wide layout in a way that does not require zooming, but will only work if you activate the scale factor to 3 (that I added in the in-game options), and use a resolution of 1920x1080 :)

I will still do some more adjustments to it related to fitting text on the wide layout.
I could also try to make the window dimensions actually fit on the wide layout but on my initial tests it just crashed, it seems to require being minimum of 800x600.

**Comment by AquariusPower** [comment]
@Asmageddon hey, good news!
https://github.com/Attnam/ivan/pull/327
I made XBRZ work for the LookZoom key mode for now, and I believe it may work on the full game window one day :)

**Comment by AquariusPower** [comment]
I was thinking (if it is not clearly explained, just ask):

The [scaled up blit](https://github.com/Attnam/ivan/pull/331) could be further intercepted. 

One day, after scaling being integrated for each square's **layer** drawing, 
instead of sourcing from a 16x16 graphics, 
we could redirect and source directly from a 64x64 graphics and then, 
instead of scaling it would blit directly the bigger image. 

Not completely sure it is really doable tho.

(I left is here as an idea/possibility)

**Comment by Asmageddon** [comment]
What about refactoring the code to make it possible to 1) draw from different-sized tilesets and/or 2) Draw the output to a buffer.

If you did 1), you could preprocess the tileset with xBRZ, hq2/3/4x, etc. and draw from that, and if you did 2, you would have a much easier time scaling the whole screen. Could be a good excuse to unspaghettify some of the code, too.

**Comment by AquariusPower** [comment]
**From what I learned, and still agreeing, just speaking differently (a bit repetitive may be):**

The moment the square is scaled up, that tiny one is no more, useless.

From that premise, all that matters is the final big tile, lets say 64x64 (x4 scale).

For every bitmap (the existing bitmap files can be split into one for each tile), an equivalent, higher resolution can be created.

Instead the game read from the 16x16 one, it would read from the bigger one (64x64) and blit it with a displacement based on the current scale (x4). **This may be the hardest part I guess...**

Advantages: 
- no need to scale up, therefore no cpu time spent on it. (despite xBRX is working quite fast to a point)
- More detailed graphics.

Anyway, the work I am doing must be fully disable-able, and until this other work is completed (by me or someone else) this work will fit well I guess :)

In the other hand xBRZ is used everywhere that required that easy workaround, practically no work from us, and may be this is the main reason it is preferable for now :).

But, mostly because we do not have access to change the applications/games it is more used in, like old DOS games. But changing them would be a highly complicated task anyway... so xBRZ is the only viable option for them, but not for Ivan! xD

**Comment by Asmageddon** [comment]
Yeah it really does sound like whatever you choose to do, you're gonna have to pick either making ugly hacks, or refactoring the rendering code :P

**Comment by AquariusPower** [comment]
Btw, after learning more about the code, I dont think it is that complex. 
After getting used to it, it is quite organized and I know much better now where to change things.
That's why I would like ppl to take a look at how I changed things to grant I am not making it more complex neither confuse.

I dont see it as exactly a "ugly" hack tho, because what they do with DOS (and Atari I guess) games is the only option.
Here not being the only option, is a hack, but as long it is disable-able, so the code doesnt depend on it to run, it is just a nice hack and a good alternative xD, until:

The real problem is: 
- what is the real deal about refactoring the rendering code? 
- what is the time and effort required to do it?
VS 
- what time we have/can/want to spend on doing it?
- who will do it?

On open source, mostly GPL code that ban commercial use, these are the questions that have to be answered.

The most we can ask is for free will donations, and we cant count on it to put food on the table...

So, at the end, the whole point is having fun doing it, for the good of self and the community :).

**Comment by fejoa** [comment]
Fixed by #331

**Comment by Asmageddon** [comment]
Oh, I was not calling xBRZ a hack, I was mostly talking about hacking it in without refactoring the code a bit, since it sounded a bit spaghetti. Either way, great work :)
