### ISSUE TITLE
broken item sells for the same value as non broken? and library prices.

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#408]
I tried that with a **golden girdle of carring +1**, 
after fixing it the selling price was still 208.

Also, being specialized vendor, the library could have diff prices than general shop.

Not sure if he should sell for less and buy for less, or sell for less and buy for more tho. Mainly to make we prefer selling/buying from him.

**Comment by red-kangaroo** [comment]
> I tried that with a golden girdle of carring +1, after fixing it the selling price was still 208.

Broken items normally  have lower price modifier defined than non-broken ones, but some (like the girdle) might be missing the lower modifier.

> Also, being specialized vendor, the library could have diff prices than general shop.

IDK, it's already preferable to sell in the library, because the shop only has limited funds and you will not be able to sell more once you take all his money, so selling in library let's you sell more.

**Comment by AquariusPower** [comment]
good point

**Comment by andrewtweber** [comment]
Somewhat related note:

I found the mantle that gives you +1 END in UT. Sold it in Attnam's shop for 3000 gold and he ran out of gold. Seems like that item is too overpriced to me (especially compared to an armor of greater health which has the same effect but would not be nearly as valuable).

**Comment by red-kangaroo** [comment]
@andrewtweber Mantle of Al-Khan? That's an artifact. In addition to increasing your endurance with enchantment as AoGH, it also grants invisibility and teleportation, so I don't think it's too overpriced.

**Comment by andrewtweber** [comment]
Ah my mistake :)

**Comment by andrewtweber** [comment]
@red-kangaroo  was the lower pricing modifier added for the new items?

**Comment by red-kangaroo** [comment]
@andrewtweber I'm not actually sure. I'll make a note to check.

**Comment by AlexMooney** [comment]
I suspect that the reason was that the object's selling price was set by the material instead of the properties of the object.  Girdle of carrying is a relatively cheap object, but a lump of solid gold is worth basically the same regardless of the shape its in.  I thought that item prices were a combination of form & material, so I still would have expected a small delta; perhaps the girdle was rounded to 0 somewhere along the way.

**Comment by red-kangaroo** [comment]
Yeah, price modifier for broken belt of carrying is lower than for unbroken, so the same price is due to high material price and rounding.

**Comment by andrewtweber** [comment]
Ok I vote to close this then since it’s a rare instance where the material is far more valuable than the item itself and the item is rightly worth the same in either form.

**Comment by AquariusPower** [comment]
interesting :>
