### ISSUE TITLE
midi file for the main menu

### ISSUE THREAD

**Issue by AquariusPower** [Attnam/ivan#422]
I was looking for some "requiem" music (quite adequate considering the background),
but I cant find a good place to hear free midi files that are compatible with this game's license,
any tips? Btw, I guess it would be CC0 or CC-BY or CC-BY-NC ? CC-BY-SA may cause a lot of trouble tho...

Also, there could have more than one midi for every place to avoid being repetitive,
despite quite good, the cathedral easily gets repetitive and I spend some time there, I usually  lower the volume to almost un-audible mostly cuz of the bells.

**Comment by fejoa** [comment]
Menu music is being worked on @AdrianGin . The midi system already allows more than one midi (in random order). 
I don't know if regular midi files will work. If they do they might sound funny because the game allocates different channels which kick in depending on how many hit points the player character has left lol.

Check out this note for more on music formatting: https://attnam.com/wiki/Music_Creation

**Comment by AdrianGin** [comment]
Hi,
'tis a labour of love! I did try to get some inspiration to do some more Ivan tracks. Had some technical difficulties with my equipment though, but I've figured it out now. Hopefully it'll not to be too far away, any suggestions for where to start / which style?

**Comment by AquariusPower** [comment]
@AdrianGin have you ever heard "I Muvrini - Requiem" ? I even got the lyrics despite I have no clue what some stuff mean :)

**Comment by andrewtweber** [comment]
Closing since it is in progress
