### ISSUE TITLE
Items spawning under non-walk-able furniture.

### ISSUE THREAD

**Issue by badbeaver** [Attnam/ivan#427]
Not much to say about this one.
![ivan_2018-06-20_18-39-00](https://user-images.githubusercontent.com/34551546/41668947-3c5a02ea-74b9-11e8-873a-c9e36bc2dcb1.png)

**Comment by andrewtweber** [comment]
I'm not a fan of the non-walkable furniture. Also occasionally produces scenarios like this:

![ijdfrizatbhqzedckrk1mqyjirwu83_1529097629](https://user-images.githubusercontent.com/2760420/41669002-4d4e503a-7476-11e8-8c0a-a80f3d9e01d3.jpg)

**Comment by AquariusPower** [comment]
instead of "fixing it",
when a new dungeon is generated,
I propose this:

from the entrance to the exit, try to create a path using the NPC AI (that is largely also used on the Wizard Autoplay mode)

If it fails, we could create a new thing called "secret wall".

How would it work?
It would be a normal wall, but illusory.
You just have to move over it and it will vanish (in look mode mode, with high perception, it could add "a strange wall").
An entire secret corridor could be created based on it to grant access to the exit w/o having a pick-axe and destructive wands.

But of course it is much easier trying to fix it :>

**Comment by AquariusPower** [comment]
@badbeaver 
> Not much to say about this one.

I am quite sure, if you kick it, the scroll may fly to the other side.
But, IMHO, imagine that scroll was very important (to it's former owner at least), that deserved be secured by the weight of an anvil, your only option would be to destroy the anvil using a strong pick-axe, but this may be excessively lore friendly I guess xD

**Comment by badbeaver** [comment]
I think that preventing furniture from spawning near doors is the best way of resolving this problem. 

But either way is fine as long as furniture stops haunting me.

**Comment by andrewtweber** [comment]
Closing for now since we have made that furniture walkable again.
