### ISSUE TITLE
Nits of Font2.png and Font3.png

### ISSUE THREAD

**Issue by iology** [Attnam/ivan#455]
@Stihdjia 

<img width="500" alt="ivanfont2" src="https://user-images.githubusercontent.com/23622455/43026624-1137641a-8ca9-11e8-9055-6efa739aaaa5.png">

<img width="500" alt="ivanfont3" src="https://user-images.githubusercontent.com/23622455/43026630-13b284ae-8ca9-11e8-82b1-b8eb29c5d679.png">

Adjustment for Font2 was proposed in #459

**Comment by Stihdjia** [comment]
I believe most of these are deliberate stylistic choices. It took me a while to figure out what I was looking at. I agree about the apostrophes though, and I've been considering changing the "f" and "h" in Font3, they're kinda bothering me too.

**Comment by iology** [comment]
These catch my eyes very easily:

Font2: The small dot (tail) of "b" is too outstanding.

Font3: The figure 5 has a big mouth. The strokes of "k, r, s, v, y" are too thin.

Font2 and Font3: The spacing around minus sign "-" (used as a hyphen between words) is obviously unbalanced.

**Comment by Stihdjia** [comment]
Almost none of the characters of any set are centered. In the original font, the hyphen looks like it's shifted to the right because it *is* centered while all other characters are strongly shifted to the left, and it's even more unbalanced than in the 3.

The "k" and "y" are kinda my favorites! There are different width strokes all over these fonts, is the only problem that the diagonal strokes don't match each other? I guess that is a little weird.

I've been pretty happy with these, especially 3, but I certainly would be opposed to a Font4.png

**Comment by iology** [comment]
Font.png is very old, so I can't really blame anyone. ;-) It is pity that the new fonts inherit the same flaws.

I think I would like Font2.png the most, but I just haven't got used to the new style. Fixing that little dot of "b" would be nice.

**Comment by Stihdjia** [comment]
I think most of the problem is the tiny 8x8 space there is to work with, including allowances for spacing and descenders. You're right, that "b" is weird. Tell it to this guy I guess, https://www.allegro.cc/forums/thread/610576 =) Also maybe we should credit that guy. 3 is an anonymous mish-mash though.

To be fair it looks a little better without the text shading IVAN uses. I'm not against fixing the "b" of 2 or the "h" and "f" of 3, a whopping edit of about almost *one whole byte*. The rest looks right to me personally.

**Comment by AquariusPower** [comment]
if the fixes makes them look too diferent, better create a Font4.png,
I actually like Font3.png a lot :)

**Comment by iology** [comment]
Maybe we should ask him to put that font on his home page: https://nitehackr.github.io/games_index.html

I will plan to adjust Font2 if nobody is against it?

**Comment by Stihdjia** [comment]
No objection here, at least not for 2.
