### ISSUE TITLE
File locations/creation on *nix

### ISSUE THREAD

**Issue by Clawzfire** [Attnam/ivan#47]
The current file layout is a mess; the only thing that are where they should be are the graphics and script files in /usr/local/share.

There's no mention of the "com" directory that the bones and highscore files are in in either the [FHS](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) or any other sources I could find, so I'm not sure where the devs got that from. These files should be in /var/lib.

The user's home directory gets (somewhat) cluttered by the save and screenshot directories, so they should probably be moved into a hidden directory along with the config file.

A structure like this would be much cleaner and conform to standards:

    /usr/(local/)bin/ivan
    
    /usr/(local/)share/ivan/─┬─Graphics/
                             └─Script/
    /var/lib/ivan/─┬─Bones/
                   └─ivan-highscore.scores
    
    
    $HOME/.ivan/─┬─Save/
                 ├─Scrshots/
                 └─ivan.conf

Also an issue is that not all files/directories are created by the game during installation/first run, leaving the user to create them manually to prevent crashes.

**Comment by emlai** [comment]
:+1: Excellent job! I've been worrying about this too. Your proposed structure looks good. I agree that the IvanSave folder in $HOME was not very nice.

**Comment by andrewtweber** [comment]
This looks good to me. @Clawzfire are you going to be working on this or was this just a suggestion?

**Comment by Clawzfire** [comment]
Just a suggestion. If it goes too long without anyone picking it up I might try to do something, but I've taken a look at it before and wasn't able to make much progress, so I'd rather leave it to someone more experienced.

**Comment by murlock** [comment]
I will work on it.

**Comment by emlai** [comment]
@murlock I've also started looking into this and got everything else sorted out except for how we're going to redefine `LOCAL_STATE_DIR` to `/var/lib/ivan`.

Since Autotools defines `localstatedir` as `${prefix}/var`, we have to do something like `localstatedir=/var/lib` in the main `configure.ac`, and then use that in
`-DLOCAL_STATE_DIR=\\\"$localstatedir/ivan\\\"`.

However then we can't (or at least I haven't found a way to) redefine the directory with e.g.
`./configure CPPFLAGS='-DLOCAL_STATE_DIR=\"/usr/local/var/ivan\"'`, which is not nice if someone needs to do it. So I'm not sure if this is the best solution. Thoughts?

**Comment by Clawzfire** [comment]
I took another look; I was able to hardcode Bones and highscores to /var/lib/ivan without any trouble (aside from having to create the actual files/directories manually), but I'm not sure if that would be a preferred method...

**Comment by emlai** [comment]
If we're going to hardcode the path then I think it's better to do it in `configure.ac` / `Makefile.am` than in the actual source code so it's easier to change when needed.

Anyway, I made some new changes (https://github.com/Attnam/ivan/compare/master...emlai:fix-file-locations) so the game now creates all files and directories properly and sets the correct permissions. I also updated/generated some of the build files required by Autotools to fix all the errors/warnings it gave me.

It works at least on my system. If you wanna test it out, just edit the local state dir definition in `configure.ac` to `-DLOCAL_STATE_DIR=\\\"$localstatedir\ivan\\\"`, and add `localstatedir=/var/lib` before that line, and regenerate the build system with `automake` and `autoconf`. And then the normal `./configure && make && sudo make install` procedure.

**Comment by Clawzfire** [comment]
I gave it a test, pretty much everything seems to be working fine, including setting `localstatedir` to /var/lib.

The only files missing are Enner.pcx and IVlad.pcx, which don't get copied to /usr/local/share during installation. It looks like these two names need to be added to Graphics/Makefile.am, after which they install normally.

**Comment by emlai** [comment]
Oh true, well spotted. Added a commit to fix that with credit to you.

**Comment by emlai** [comment]
I propose that we merge [my branch](https://github.com/Attnam/ivan/compare/master...emlai:fix-file-locations) now as it is, since it works and all, and is better than the current build configuration anyways.

If we someday find a better way to set up the `localstatedir` then we can change just that. Or if the GNU Autotools start conforming to HFS3 then we can just remove it.
