### ISSUE TITLE
Make all StringQuestions escapable?

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#48]
You can cancel reading all other kinds of (non-instantaneous) scrolls, so it would be nice to be able to do so with scrolls of detect material as well. Or is there a specific reason why this is not allowed?

**Comment by Clawzfire** [comment]
Looks like there are two components to this (using scroll of wishing as an example because it also behaves this way): 

1. The [`Wish` function in game.cpp](https://github.com/Attnam/ivan/blob/master/Main/Source/game.cpp#L3107) calls `DefaultQuestion`, which passes `AllowExit=false` to `StringQuestion`. A parameter could be added to the `DefaultQuestion` function to set `AllowExit` and pass it along, or it could just be set to true as the default, though this may cause problems with certain questions (such as forced polycontrol, though you *do* have the option of transforming into a human to avoid polymorphing).

2. `Wish` (as well as scroll of detect material and probably other prompts using `DefaultQuestion`) run infinite loops until good input is received, so even allowing exit with ESC will just call the question again unless the function has a case added to handle an aborted prompt.

**Comment by emlai** [comment]
Ah, forgot to test scrolls of wishing. And yes the forced polycontrol question is annoying too. Also `commandsystem::SummonMonster` and the `"What material do you want to wish for?"` part in scroll of change material seem to be unescapable. Should we make all these five escapable?

`iosystem::StringQuestion` has already implemented the possibility to abort so we could just make use of it in `game::StringQuestion` and its call site.

**Comment by Clawzfire** [comment]
There are 5 calls to `DefaultQuestion` in the code, for the following prompts:

1. Scroll of Change Material

2. Scroll of Detect Material

3. Wishing

4. PolyControl

5. Summoning monsters in Wizard mode.

The only one that I can see causing issues is the wishing, since this applies to scrolls as well as fountains and genies; if a player cancels a genie's wish it would be gone, so non-scroll wishes shouldn't be escapable.

Aside from that I'm all for the others being escapable.

**Comment by andrewtweber** [comment]
I can't think of any reason for them not to be. I know I've experienced that before and it annoyed me. I say remove them except the non-scroll wishes!

**Comment by emlai** [comment]
Sounds good. I'm working on this right now. Pull request incoming… soon.
