### ISSUE TITLE
abnormal situation. doesn't make sense.

### ISSUE THREAD

**Issue by nsklaus** [Attnam/ivan#522]
please look at the screenshot.
i have full health. now, look at the message console. 
was i hit by a supernatural viking rat ? no. console just say: "a large rat".
so i died because i was starved ? it seems it's the only possibility. but then,
have you ever seen someone starving up to the point of dying ? he certainly shouldn't have "full HP".

so to resume: i have full health, good armor, i suddenly see a large rat, and i just die. 
please, fix your game. 
this is not normal case. 
and don't tell me it's called "Iter Vehemens ad Necem (IVAN)" for that kind of reason.
thank you.
![screenshot_20190112_142134](https://user-images.githubusercontent.com/6810861/51073731-b5e24380-1675-11e9-82c1-cb23fb41ef11.png)

**Comment by nsklaus** [comment]
> Yes, you starved to death. "Starving!" is written there in red and with an exclamation mark for a reason.
> 
> Thank you.

it should not display full health then ? 
starving status should be draining health and lead to display: HP 1/36 instead.
it would make more sense. because, dying with full health seems like a non-sense.
in any case, once i'm dead it should also show HP 0/36.

**Comment by andrewtweber** [comment]
HP indicates damage to body parts. Starving doesn't cause any damage to your body parts therefore it's not reflected by your HP. And that's why that information is presented to the user differently, i.e. in the "Starving!" red text. 

There are also other ways for the character to die with more than 0 HP. Each body part has its own HP. The head, groin, and torso are considered critical body parts. If either of those individual body parts is destroyed it will kill you even if your limbs are in good health.

**Comment by andrewtweber** [comment]
Also worth noting that sometimes when the character is ill (vomiting a lot), this causes the player's Endurance to drop, which results in a decreased overall HP. You can think of this as the entire body getting weaker due to poor health. I believe frequent hunger can also have the same effect.

**Comment by AquariusPower** [comment]
"starving status should be draining health", as "I" remember, your char also feel asleep a few times out of starvation. Temporary lowered endurance would still not hint you enough, despite a nice new feature, would actually probably hint less than "starving!" and falling asleep...

I think what you are looking for is **a better hint about starvation**, when very near death because of starvation a popup red alert should show up saying "you should eat something now!", if you dont, in about 3 turns your char dies, that kind of hint is un-ignore-able on a fast play, but could instead just be a new pain sound based in some log message :)

PS.: when I first played long ago, one of my chars also died like that lol!
