### ISSUE TITLE
Game crashes when you turn on fullscreen mode

### ISSUE THREAD

**Issue by andrewtweber** [Attnam/ivan#80]
Confirmed on 64-bit Windows 8 and 10
Not sure about OSX / Linux

**Comment by Clawzfire** [comment]
Resizing/forcing full screen/letting the game set full screen/any other abuse of the windows all works without trouble on 64-bit Linux.

**Comment by emlai** [comment]
On OS X, entering fullscreen works as expected, but exiting fullscreen doesn't. When the game is launched in fullscreen mode, and then reverted to windowed mode,  one of these two things happens (apparently randomly):
- either the window becomes invisible, with no way to show it again without quitting and relaunching,
- or the graphics start looking weird, like this:
 
 <img width="912" alt="screen shot 2016-01-17 at 03 52 24" src="https://cloud.githubusercontent.com/assets/7543552/12375520/ba5ca936-bcce-11e5-8a7e-22fcd02e859a.png">

 This looks like nearest-neighbor interpolation so it's probably caused by [this](https://github.com/Attnam/ivan/blob/master/FeLib/Source/graphics.cpp#L181). Notice especially the letters that look a bit different than usual. Also the window title is missing. Normally it would look like this:
 
 <img width="912" alt="screen shot 2016-01-17 at 03 52 38" src="https://cloud.githubusercontent.com/assets/7543552/12375522/bceffaa4-bcce-11e5-9752-da8db614779b.png">

I will try to fix these so we can see whether it fixes the Windows problem as well.

**Comment by emlai** [comment]
This might be a bug in SDL2 because I tested this with SDL 2.0.3 (instead of 2.0.4) and the behavior was different (but still wrong).

**Comment by fejoa** [comment]
It crashes on Windows 7 as well.

**Comment by emlai** [comment]
For some reason, the OS X problem goes away after adding `SDL_SetWindowSize(Window, Res.X, Res.Y);` just before https://github.com/Attnam/ivan/blob/master/FeLib/Source/graphics.cpp#L307. Does this fix the Windows problem too?

If not, can you check what the return value of `SDL_SetWindowFullscreen` is? It should return `0` on success.

**Comment by fejoa** [comment]
So I added `SDL_SetWindowSize(Window, Res.X, Res.Y);` just before [graphics.cpp#L307](https://github.com/Attnam/ivan/blob/b4610387ffe544627e4b3c6bfd7c1406e6a746ca/FeLib/Source/graphics.cpp#L307) and it didn't fix the problem. 
The return value of `SDL_SetWindowFullscreen` is `0` when I outputted it using `ABORT()`

Any other ideas?

**Comment by fejoa** [comment]
If you open the ivan.cgf file you can change the fullscreen configuration no problem. It crashes only when you try to change the config in-game.
I've isolated the problem to the [`SDL_RenderClear`](https://github.com/Attnam/ivan/blob/b4610387ffe544627e4b3c6bfd7c1406e6a746ca/FeLib/Source/graphics.cpp#L265) function so far, though I don't yet know why the crash happens at this point.

**Comment by emlai** [comment]
What if you change all instances of `SDL_WINDOW_FULLSCREEN_DESKTOP` to `SDL_WINDOW_FULLSCREEN` on Windows? Does this change anything?

**Comment by fejoa** [comment]
Does [this line](https://github.com/Attnam/ivan/blob/master/FeLib/Source/graphics.cpp#L247) ever execute under Linux or Mac?

**Comment by emlai** [comment]
It does when `SDL_BYTEORDER == SDL_BIG_ENDIAN`, and then it's a compilation error.

**Comment by fejoa** [comment]
I wondered whether that was the case. I was just curious. All the same, it's not relevant to the bug at hand.

So basically all the three major platforms use the same code in `BlitDBToScreen`, and the results are wildly different between Linux (stable) and Windows (crash).
I'm going to try talk to the guys over at the [SDL forums](https://forums.libsdl.org/index.php), because this bug is looking increasingly opaque.

**Comment by andrewtweber** [comment]
#133 reports that this was working in 504 but broke as of 505. Not sure if that was new information or not.

**Comment by fejoa** [comment]
I just checked and v0504 has the full screen bug too :(

**Comment by emlai** [comment]
There are occasional problems in switching to/from fullscreen on Mac and Linux too, so I'll edit the title to reflect that.

**Comment by emlai** [comment]
The fullscreen toggle bug on Mac is an SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=3501
