### ISSUE TITLE
Make "smart" open/close/use behavior toggleable

### ISSUE THREAD

**Issue by emlai** [Attnam/ivan#85]
I feel that the "smarter" open / close / use key behavior I introduced in #41 is not that great after all. I have had this feeling for quite a long time now so I think probably others will agree with me.

It's particularly annoying when this feature causes something other than what you expected to happen. Originally there wasn't this problem, as all these actions resulted in the same behavior every time. This would also follow the "keep it simple" principle.

Anyway, there are still at least two commits in the PR (dff58af and 612ff5f), that I think are useful, and should be left as is.

What do you think? Should we revert this feature?

**Comment by Clawzfire** [comment]
While I'm biased since the new behavior is messing with my muscle memory, I'm
still for reverting to the original behavior, or making it a toggle-able
option.

**Comment by andrewtweber** [comment]
> It's particularly annoying when this feature causes something other than what you expected to happen. 

Can you give an example?

I think I would vote for making it toggle-able too

**Comment by fejoa** [comment]
Yeah, I can't say I've had particular trouble with it, but it hasn't been the focus of my play-testing.
It's up to you whether you want to revert. Your intuition is giving you second thoughts and you should listen to that because it's one of the pillars of wisdom. 
I can say I found it pleasant to walk up to a chest and simply press the 'o' key and it would open, without the need to tell the game where the item to be opened is located, which I find really clunky.
As above, can you give an example of what you think are some shortcomings? I'm pro toggle switch, if you feel this would be ok.

**Comment by emlai** [comment]
> Can you give an example?

It's probably because of muscle memory as Clawzfire mentioned. For example, when I open a chest, I see some message appear in the top bar out of the corner of my eye, and think it's the "choose direction" message although it's the "take or put" message. Then I enter a direction instead of 't' or 'p'. This still happens after playing this way for .

Another example is when you're standing next to a big pile of items with a chest among them, but you don't know it's there. There's also a different chest (or a door) next to you that you're trying to open. You press 'o' and quickly 't' or 'p' to respond to the "take or put" message that you're expecting. But instead it asks for a direction.

This has the disadvantage that you can't always 100% accurately predict the message (which is useful when you're typing commands fast), and you have to slow yourself down a bit to actually read the messages.

I think making this behavior toggle-able would be the right thing to do, as it has its advantages and disadvantages.

**Comment by andrewtweber** [comment]
I took a long enough break from IVAN that the new style doesn't bother me.

But you're right about not 100% being able to key through the commands without reading.

I would make it toggleable and keep it on (no direction confirmation) by default, so that new people coming from other roguelikes where it's the default behavior have an easier time getting into it.

**Comment by emlai** [comment]
Yeah. I'll start working on making it toggle-able. No direction confirmation seems like a good default.
